<?php
$color_selector                      = array(
	'.qodef-h1',
	'h1',
	'.qodef-h1 a:hover',
	'h1 a:hover',
	'.qodef-h2',
	'h2',
	'.qodef-h2 a:hover',
	'h2 a:hover',
	'.qodef-h3',
	'h3',
	'.qodef-h3 a:hover',
	'h3 a:hover',
	'.qodef-h4',
	'h4',
	'.qodef-h4 a:hover',
	'h4 a:hover',
	'.qodef-h5',
	'h5',
	'.qodef-h5 a:hover',
	'h5 a:hover',
	'.qodef-h6',
	'h6',
	'.qodef-h6 a:hover',
	'h6 a:hover',
	'a:hover',
	'p a:hover',
	'blockquote',
	'input[type=email]:focus',
	'input[type=number]:focus',
	'input[type=password]:focus',
	'input[type=tel]:focus',
	'input[type=text]:focus',
	'input[type=url]:focus',
	'textarea:focus',
	'#qodef-page-footer input[type=email]:focus',
	'#qodef-page-footer input[type=number]:focus',
	'#qodef-page-footer input[type=password]:focus',
	'#qodef-page-footer input[type=tel]:focus',
	'#qodef-page-footer input[type=text]:focus',
	'#qodef-page-footer input[type=url]:focus',
	'#qodef-page-footer textarea:focus',
	'button[type=submit]',
	'input[type=submit]',
	'body .select2-container--default.select2-container--open .select2-selection--multiple',
	'body .select2-container--default.select2-container--open .select2-selection--single',
	'body .select2-container--default .select2-selection--single',
	'body .select2-container--default .select2-selection--single .select2-selection__arrow',
	'body .select2-container--default .select2-selection--multiple',
	'body .select2-container--default .select2-search--dropdown .select2-search__field:focus',
	'body .select2-container--default .select2-results__option[aria-disabled=true]',
	'body .select2-container--default .select2-results__option[aria-selected=true]',
	'body .select2-container--default .select2-results__option[data-selected=true]',
	'body .select2-container--default .select2-results__option--highlighted[aria-selected]',
	'#qodef-page-header .widget_icl_lang_sel_widget .wpml-ls-legacy-dropdown .wpml-ls-item-toggle:hover',
	'#qodef-page-header .widget_icl_lang_sel_widget .wpml-ls-legacy-dropdown-click .wpml-ls-item-toggle:hover',
	'#qodef-page-header .widget_icl_lang_sel_widget .wpml-ls-legacy-dropdown .wpml-ls-sub-menu .wpml-ls-item a:hover',
	'#qodef-page-header .widget_icl_lang_sel_widget .wpml-ls-legacy-dropdown-click .wpml-ls-sub-menu .wpml-ls-item a:hover',
	'#qodef-page-header .widget_icl_lang_sel_widget .wpml-ls-legacy-list-horizontal ul li a:hover',
	'#qodef-page-header .widget_icl_lang_sel_widget .wpml-ls-legacy-list-vertical ul li a:hover',
	'#qodef-page-mobile-header .widget_icl_lang_sel_widget .wpml-ls-legacy-dropdown .wpml-ls-item-toggle:hover',
	'#qodef-page-mobile-header .widget_icl_lang_sel_widget .wpml-ls-legacy-dropdown-click .wpml-ls-item-toggle:hover',
	'#qodef-page-mobile-header .widget_icl_lang_sel_widget .wpml-ls-legacy-dropdown .wpml-ls-sub-menu .wpml-ls-item a:hover',
	'#qodef-page-mobile-header .widget_icl_lang_sel_widget .wpml-ls-legacy-dropdown-click .wpml-ls-sub-menu .wpml-ls-item a:hover',
	'#qodef-page-mobile-header .widget_icl_lang_sel_widget .wpml-ls-legacy-list-horizontal ul li a:hover',
	'#qodef-page-mobile-header .widget_icl_lang_sel_widget .wpml-ls-legacy-list-vertical ul li a:hover',
	'#qodef-page-sidebar .widget_icl_lang_sel_widget .wpml-ls-legacy-dropdown .wpml-ls-item-toggle:hover',
	'#qodef-page-sidebar .widget_icl_lang_sel_widget .wpml-ls-legacy-dropdown-click .wpml-ls-item-toggle:hover',
	'#qodef-page-sidebar .widget_icl_lang_sel_widget .wpml-ls-legacy-dropdown .wpml-ls-sub-menu .wpml-ls-item a:hover',
	'#qodef-page-sidebar .widget_icl_lang_sel_widget .wpml-ls-legacy-dropdown-click .wpml-ls-sub-menu .wpml-ls-item a:hover',
	'#qodef-page-sidebar .widget_icl_lang_sel_widget .wpml-ls-legacy-list-horizontal ul li a:hover',
	'#qodef-page-sidebar .widget_icl_lang_sel_widget .wpml-ls-legacy-list-vertical ul li a:hover',
	'#qodef-page-footer .widget_icl_lang_sel_widget .wpml-ls-legacy-dropdown .wpml-ls-item-toggle:hover',
	'#qodef-page-footer .widget_icl_lang_sel_widget .wpml-ls-legacy-dropdown-click .wpml-ls-item-toggle:hover',
	'#qodef-page-footer .widget_icl_lang_sel_widget .wpml-ls-legacy-dropdown .wpml-ls-sub-menu .wpml-ls-item a:hover',
	'#qodef-page-footer .widget_icl_lang_sel_widget .wpml-ls-legacy-dropdown-click .wpml-ls-sub-menu .wpml-ls-item a:hover',
	'#qodef-side-area .widget_icl_lang_sel_widget .wpml-ls-legacy-dropdown .wpml-ls-item-toggle:hover',
	'#qodef-side-area .widget_icl_lang_sel_widget .wpml-ls-legacy-dropdown-click .wpml-ls-item-toggle:hover',
	'#qodef-side-area .widget_icl_lang_sel_widget .wpml-ls-legacy-dropdown .wpml-ls-sub-menu .wpml-ls-item a:hover',
	'#qodef-side-area .widget_icl_lang_sel_widget .wpml-ls-legacy-dropdown-click .wpml-ls-sub-menu .wpml-ls-item a:hover',
	'.qodef-blog article .qodef-e-info-category a:hover',
	'.qodef-blog article .qodef-e-info-date a:hover',
	'.qodef-blog article .qodef-e-info-tags a:hover',
	'.qodef-blog article .qodef-e-single-links .qodef-e-single-links-title',
	'.qodef-blog article .qodef-e-single-links a',
	'.qodef-blog article .qodef-e-single-links>span:not(.qodef-e-single-links-title)',
	'.qodef-blog article .qodef-e-single-links>span:not(.qodef-e-single-links-title)',
	'#qodef-page-comments-list .qodef-comment-item .qodef-e-date a:hover',
	'.wp-block-button.is-style-outline .wp-block-button__link',
	'.wp-block-archives li a',
	'.wp-block-categories li a',
	'.wp-block-latest-posts li a',
	'.wp-block-archives li a:hover',
	'.wp-block-categories li a:hover',
	'.wp-block-latest-posts li a:hover',
	'blockquote.wp-block-pullquote',
	'.wp-block-pullquote blockquote',
	'.wp-block-quote',
	'#qodef-mobile-header-opener',
	'#qodef-mobile-header-navigation .qodef-m-inner>ul>li>a',
	'body:not([class*=banquet-core]) #qodef-mobile-header-navigation ul li.menu-item-has-children>a:after',
	'#qodef-back-to-top .qodef-back-to-top-icon',
	'.qodef-fullscreen-menu-holder nav.qodef-fullscreen-menu ul li.current-menu-ancestor>a',
	'.qodef-fullscreen-menu-holder nav.qodef-fullscreen-menu ul li.current-menu-item>a',
	'.qodef-fullscreen-menu-holder nav.qodef-fullscreen-menu ul li ul li.current-menu-ancestor>a',
	'.qodef-fullscreen-menu-holder nav.qodef-fullscreen-menu ul li ul li.current-menu-item>a',
	'#qodef-page-header .qodef-header-navigation>ul#qodef-sticky-navigation-menu>li>a',
	'.qodef-header-navigation ul li.qodef-menu-item--wide .qodef-drop-down-second .qodef-drop-down-second-inner>ul>li>a',
	'.qodef-team-list .qodef-team-member-social-links a:hover',
	'.qodef-testimonials-list .qodef-e-author-job',
	'.qodef-fullscreen-search-holder .qodef-search-field:focus',
	'.qodef-fullscreen-search-holder .qodef-search-submit:hover',
	'.qodef-fullscreen-search-holder .qodef-search-close:hover',
	'.qodef-accordion.qodef-layout--simple .qodef-accordion-title.ui-state-active',
	'.qodef-accordion.qodef-layout--simple .qodef-accordion-title.ui-state-hover',
	'.qodef-button.qodef-layout--outlined',
	'.qodef-countdown.qodef-layout--simple .qodef-digit',
	'.qodef-counter.qodef-layout--simple .qodef-m-digit',
	'.qodef-dropcaps .qodef-m-letter',
	'.qodef-pricing-table .qodef-m-title p',
	'.qodef-pricing-table .qodef-m-content ul li',
	'.qodef-progress-bar:not(.qodef-layout--line) .progressbar-text',
	'.qodef-tabs.qodef-layout--simple .qodef-tabs-navigation li a:hover',
	'.qodef-tabs.qodef-layout--simple .qodef-tabs-navigation li.ui-state-active a',
	'.qodef-tabs.qodef-layout--simple .qodef-tabs-navigation li.ui-state-hover a',
	'.qodef-video-button .qodef-m-play',
	'.qodef-side-area-opener:hover',
	'.qodef-social-share .qodef-social-title',
	'.qodef-social-share li.qodef-facebook-share a:hover',
	'.qodef-social-share li.qodef-twitter-share a:hover',
	'.qodef-social-share li.qodef-linkedin-share a:hover',
	'.qodef-social-share li.qodef-tumblr-share a:hover',
	'.qodef-social-share li.qodef-pinterest-share a:hover',
	'.qodef-social-share li.qodef-vk-share a:hover',
	'#qodef-page-sidebar .widget .qodef-social-share.qodef-layout--text li.qodef-facebook-share a:hover',
	'#qodef-page-sidebar .widget .qodef-social-share.qodef-layout--text li.qodef-twitter-share a:hover',
	'#qodef-page-sidebar .widget .qodef-social-share.qodef-layout--text li.qodef-linkedin-share a:hover',
	'#qodef-page-sidebar .widget .qodef-social-share.qodef-layout--text li.qodef-tumblr-share a:hover',
	'#qodef-page-sidebar .widget .qodef-social-share.qodef-layout--text li.qodef-pinterest-share a:hover',
	'#qodef-page-sidebar .widget .qodef-social-share.qodef-layout--text li.qodef-vk-share a:hover',
	'#qodef-page-footer .widget .qodef-social-share.qodef-layout--text li.qodef-facebook-share a:hover',
	'#qodef-page-footer .widget .qodef-social-share.qodef-layout--text li.qodef-twitter-share a:hover',
	'#qodef-page-footer .widget .qodef-social-share.qodef-layout--text li.qodef-linkedin-share a:hover',
	'#qodef-page-footer .widget .qodef-social-share.qodef-layout--text li.qodef-tumblr-share a:hover',
	'#qodef-page-footer .widget .qodef-social-share.qodef-layout--text li.qodef-pinterest-share a:hover',
	'#qodef-page-footer .widget .qodef-social-share.qodef-layout--text li.qodef-vk-share a:hover',
	'#qodef-side-area .widget .qodef-social-share.qodef-layout--text li.qodef-facebook-share a:hover',
	'#qodef-side-area .widget .qodef-social-share.qodef-layout--text li.qodef-twitter-share a:hover',
	'#qodef-side-area .widget .qodef-social-share.qodef-layout--text li.qodef-linkedin-share a:hover',
	'#qodef-side-area .widget .qodef-social-share.qodef-layout--text li.qodef-tumblr-share a:hover',
	'#qodef-side-area .widget .qodef-social-share.qodef-layout--text li.qodef-pinterest-share a:hover',
	'#qodef-side-area .widget .qodef-social-share.qodef-layout--text li.qodef-vk-share a:hover',
	'#qodef-page-spinner .qodef-m-inner',
	'.qodef-twitter-list.qodef-layout--columns #ctf .ctf-author-name',
	'#qodef-woo-page .qodef-woo-ratings .qodef-m-star',
	'.qodef-woo-shortcode .qodef-woo-ratings .qodef-m-star',
	'#qodef-woo-page .added_to_cart',
	'#qodef-woo-page .button',
	'.qodef-woo-shortcode .added_to_cart',
	'.qodef-woo-shortcode .button',
	'#qodef-woo-page .quantity input[type=number]',
	'.woocommerce-page div.woocommerce .shop_table th',
	'.woocommerce-page div.woocommerce>.cart-empty',
	'.woocommerce-page div.woocommerce>.return-to-shop a',
	'#qodef-woo-page.qodef--checkout .wc_payment_methods label',
	'.woocommerce-account .woocommerce-MyAccount-navigation ul li.is-active a',
	'.woocommerce-account .button',
	'.woocommerce-order-received .woocommerce-order .woocommerce-thankyou-order-received',
	'.woocommerce-order-received .woocommerce-order h2',
	'#qodef-woo-page .woocommerce-pagination .page-numbers',
	'.qodef-woo-product-list .qodef-woo-product-inner:hover .qodef-woo-product-title',
	'.qodef-woo-product-list .qodef-woo-product-categories a:hover',
	'#qodef-woo-page .qodef-quantity-buttons .qodef-quantity-input',
	'.woocommerce-page .qodef-content .qodef-quantity-buttons .qodef-quantity-input',
	'#qodef-woo-page .qodef-quantity-buttons .qodef-quantity-minus:hover',
	'#qodef-woo-page .qodef-quantity-buttons .qodef-quantity-plus:hover',
	'.woocommerce-page .qodef-content .qodef-quantity-buttons .qodef-quantity-minus:hover',
	'.woocommerce-page .qodef-content .qodef-quantity-buttons .qodef-quantity-plus:hover',
	'#qodef-woo-page.qodef--single .woocommerce-product-rating .woocommerce-review-link:hover',
	'#qodef-woo-page.qodef--single form.cart.grouped_form .group_table label',
	'#qodef-woo-page.qodef--single form.cart .variations label',
	'#qodef-woo-page.qodef--single .out-of-stock',
	'#qodef-woo-page.qodef--single .product_meta .qodef-woo-meta-label',
	'#qodef-woo-page.qodef--single .product_meta .qodef-social-share .qodef-social-title',
	'#qodef-woo-page.qodef--single .product_meta .qodef-woo-meta-value a:hover',
	'#qodef-woo-page.qodef--single .product_meta .qodef-woo-meta-value:hover',
	'#qodef-woo-page.qodef--single .qodef-social-share .qodef-social-title',
	'#qodef-woo-page.qodef--single .qodef-quantity-buttons:before',
	'#qodef-woo-page.qodef--single .woocommerce-tabs .wc-tabs li a:hover',
	'#qodef-woo-page.qodef--single .woocommerce-tabs .wc-tabs li.active a',
	'#qodef-woo-page.qodef--single .shop_attributes th',
	'#qodef-woo-page.qodef--single .woocommerce-Reviews .woocommerce-review__author',
	'#qodef-woo-page.qodef--single #review_form .comment-reply-title',
	'#qodef-woo-page.qodef--single #review_form .comment-form-rating a:before',
	'#qodef-woo-page.qodef--single #review_form .comment-form-rating a.active:after',
	'.widget.woocommerce .qodef-woo-ratings .qodef-m-star',
	'.widget.woocommerce .button',
	'.widget.widget_layered_nav ul li.chosen a',
	'.widget.widget_products .qodef-woo-product-title a:hover',
	'.widget.widget_recently_viewed_products .qodef-woo-product-title a:hover',
	'.widget.widget_top_rated_products .qodef-woo-product-title a:hover',
	'.widget.widget_recent_reviews a',
	'.widget.widget_recent_reviews a:hover',
	'#qodef-page-footer .widget.widget_layered_nav ul li.chosen a',
	'#qodef-page-footer .widget.widget_products .qodef-woo-product-title a:hover',
	'#qodef-page-footer .widget.widget_recently_viewed_products .qodef-woo-product-title a:hover',
	'#qodef-page-footer .widget.widget_top_rated_products .qodef-woo-product-title a:hover',
	'#qodef-page-footer .widget.widget_recent_reviews a',
	'#qodef-page-footer .widget.widget_recent_reviews a:hover',
	'#qodef-page-sidebar .widget.widget_layered_nav ul li.chosen a',
	'#qodef-page-sidebar .widget.widget_products .qodef-woo-product-title a:hover',
	'#qodef-page-sidebar .widget.widget_recently_viewed_products .qodef-woo-product-title a:hover',
	'#qodef-page-sidebar .widget.widget_top_rated_products .qodef-woo-product-title a:hover',
	'#qodef-page-sidebar .widget.widget_recent_reviews a',
	'#qodef-page-sidebar .widget.widget_recent_reviews a:hover',
	'.qodef-woo-dropdown-cart .qodef-m-opener',
	'#qodef-top-area .qodef-woo-dropdown-cart .qodef-woo-dropdown-items a:hover',
	'.qodef-woo-dropdown-cart .qodef-e-title a'
);
$background_color_selector           = array(
	'body .select2-container--default .select2-selection--multiple .select2-selection__rendered .select2-selection__choice',
	'.qodef-m-filter .qodef-m-filter-item.qodef--active',
	'.qodef-m-filter .qodef-m-filter-item:hover',
	'.wp-block-button .wp-block-button__link',
	'.wp-block-file .wp-block-file__button',
	'.has-primary-background-color',
	'#qodef-back-to-top:hover .qodef-back-to-top-icon',
	'.qodef-button.qodef-layout--filled.qodef-html--link',
	'.qodef-dropcaps:not(.qodef-type--simple) .qodef-m-letter',
	'.qodef-highlight .qodef-highlight-text',
	'.qodef-icon-holder.qodef-layout--circle',
	'.qodef-icon-holder.qodef-layout--square',
	'.qodef-icon-holder.qodef-layout--circle:hover',
	'.qodef-icon-holder.qodef-layout--square:hover',
	'#qodef-page-spinner.qodef-layout--progress-bar .qodef-m-spinner-line-front',
	'#qodef-woo-page .qodef-woo-product-mark',
	'.qodef-woo-shortcode .qodef-woo-product-mark',
	'.widget.widget_price_filter .price_slider_wrapper .ui-widget-content .ui-slider-handle',
	'.widget.widget_price_filter .price_slider_wrapper .ui-widget-content .ui-slider-range',
	'#qodef-page-footer .widget.widget_price_filter .price_slider_wrapper .ui-widget-content .ui-slider-handle',
	'#qodef-page-footer .widget.widget_price_filter .price_slider_wrapper .ui-widget-content .ui-slider-range',
	'#qodef-page-sidebar .widget.widget_price_filter .price_slider_wrapper .ui-widget-content .ui-slider-handle',
	'#qodef-page-sidebar .widget.widget_price_filter .price_slider_wrapper .ui-widget-content .ui-slider-range',
	'.qodef-woo-dropdown-cart .qodef-m-action-link'
);
$background_color_important_selector = array( '.qodef-blog .mejs-container .mejs-controls' );
$border_color_selector               = array(
	'input[type=email]:focus',
	'input[type=number]:focus',
	'input[type=password]:focus',
	'input[type=tel]:focus',
	'input[type=text]:focus',
	'input[type=url]:focus',
	'textarea:focus',
	'#qodef-page-footer input[type=email]',
	'#qodef-page-footer input[type=number]',
	'#qodef-page-footer input[type=password]',
	'#qodef-page-footer input[type=tel]',
	'#qodef-page-footer input[type=text]',
	'#qodef-page-footer input[type=url]',
	'#qodef-page-footer textarea',
	'body .select2-container--default .select2-search--inline .select2-search__field:focus',
	'body .select2-container--default .select2-search--dropdown .select2-search__field:focus',
	'.swiper-pagination-bullets .swiper-pagination-bullet-active:after',
	'#qodef-back-to-top:hover .qodef-back-to-top-icon',
	'.qodef-sp-holder .qodef-sp-prevent-input'
);
$color_important_selector            = array( '.qodef-woo-dropdown-cart .qodef-m-action .qodef-m-action-link' );
